/*
* Java bean class
* Created on 25 mars 2015 ( Date ISO 2015-03-25 - Time 17:26:44 )
* Generated by Telosys Tools Generator ( version 2.1.1 )
*/

package org.demo.repository;

import java.io.Serializable;

import java.util.Date;

import org.springframework.data.repository.PagingAndSortingRepository;
import org.demo.bean.Employee;

/**
 * Repository
 *
 * @author Telosys Tools Generator
 *
 */
public class EmployeeRepository extends PagingAndSortingRepository<Employee, String>
{

}
