/*
* Java bean class
* Created on 26 mars 2015 ( Date ISO 2015-03-26 - Time 17:42:04 )
* Generated by Telosys Tools Generator ( version 2.1.1 )
*/

package org.demo.repository;

import java.io.Serializable;

import java.util.Date;

import org.springframework.data.repository.PagingAndSortingRepository;
import org.demo.bean.Employee;

/**
 * Repository
 *
 * @author Telosys Tools Generator
 *
 */
public interface EmployeeRepository extends PagingAndSortingRepository<Employee, String>
{

}
