[]
/*
 * Java bean class
 * Created on 25 mars 2015 ( Date ISO 2015-03-25 - Time 17:26:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.bean;

import java.io.Serializable;

import java.util.Date;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Entity bean
 *
 * @author Telosys Tools Generator
 *
 */
@Document(collection = "employee")
public class Employee implements Serializable
{
    private static final long serialVersionUID = 1L;


    private Date       birthDate    ;
    private String     firstName    ;
    private            country      ;
    private Integer    id           ;

    /**
     * Default constructor
     */
    public Employee()
    {
        super();
    }
    
    /**
     * Set the "birthDate" field value
     * @param birthDate
     */
    public void setBirthDate( Date birthDate )
    {
        this.birthDate = birthDate;
    }
        
    /**
     * Get the "birthDate" field value
     * @return the field value
     */
    public Date getBirthDate()
    {
        return this.birthDate;
    }
        
    /**
     * Set the "firstName" field value
     * @param firstName
     */
    public void setFirstName( String firstName )
    {
        this.firstName = firstName;
    }
        
    /**
     * Get the "firstName" field value
     * @return the field value
     */
    public String getFirstName()
    {
        return this.firstName;
    }
        
    /**
     * Set the "country" field value
     * @param country
     */
    public void setCountry(  country )
    {
        this.country = country;
    }
        
    /**
     * Get the "country" field value
     * @return the field value
     */
    public  getCountry()
    {
        return this.country;
    }
        
    /**
     * Set the "id" field value
     * @param id
     */
    public void setId( Integer id )
    {
        this.id = id;
    }
        
    /**
     * Get the "id" field value
     * @return the field value
     */
    public Integer getId()
    {
        return this.id;
    }
    
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(birthDate);
        sb.append("|");
        sb.append(firstName);
        sb.append("|");
        sb.append(country);
        sb.append("|");
        sb.append(id);
        return sb.toString(); 
    } 


}
